language: erlang

otp_release:
  - 18.2
  - 17.5
  - R15B03

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - llvm-3.6

before_install:
  - sudo apt-get update -qq
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-system1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-system1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-atomic1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-atomic1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-chrono1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-serialization1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-serialization1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-chrono1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-date-time1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-date-time1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-thread1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/b/boost1.55/libboost-thread1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/universe/r/re2/libre2-1_20140304+dfsg-2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/universe/r/re2/libre2-dev_20140304+dfsg-2_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf-dev_2.6.1-1_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/universe/libp/libphonenumber/libphonenumber6_6.0+r655-0ubuntu6_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/universe/libp/libphonenumber/libphonenumber-dev_6.0+r655-0ubuntu6_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf9_2.6.1-1_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf-lite9_2.6.1-1_amd64.deb
  - sudo dpkg -i libboost1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-system1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-system1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-atomic1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-chrono1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-serialization1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-serialization1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-date-time1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-atomic1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-chrono1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-date-time1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-thread1.55.0_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo dpkg -i libboost-thread1.55-dev_1.55.0+dfsg-3ubuntu2_amd64.deb
  - sudo apt-get install -y cmake
  - sudo apt-get install -y cmake-curses-gui
  - sudo apt-get install -y libgtest-dev
  - sudo dpkg -i libre2-1_20140304+dfsg-2_amd64.deb
  - sudo dpkg -i libre2-dev_20140304+dfsg-2_amd64.deb
  - sudo dpkg -i libicu52_52.1-8_amd64.deb
  - sudo dpkg -i libprotobuf9_2.6.1-1_amd64.deb
  - sudo dpkg -i libprotobuf-lite9_2.6.1-1_amd64.deb
  - sudo dpkg -i libprotobuf-dev_2.6.1-1_amd64.deb
  - sudo apt-get install -y maven-debian-helper
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y default-jdk-doc
  - sudo apt-get install -y junit4
  - sudo apt-get install -y libbuild-helper-maven-plugin-java
  - sudo apt-get install -y libmaven-antrun-plugin-java
  - sudo apt-get install -y libmaven-assembly-plugin-java
  - sudo apt-get install -y libmaven-compiler-plugin-java
  - sudo apt-get install -y libmaven-exec-plugin-java
  - sudo apt-get install -y libmaven-jar-plugin-java
  - sudo apt-get install -y libmaven-javadoc-plugin-java
  - sudo apt-get install -y libmaven-war-plugin-java
  - sudo apt-get install -y libprotobuf-java
  - sudo apt-get install -y libservlet2.5-java
  - sudo apt-get install -y libservlet2.5-java-doc
  - sudo apt-get install -y cdbs
  - sudo dpkg -i libphonenumber6_6.0+r655-0ubuntu6_amd64.deb
  - sudo dpkg -i libphonenumber-dev_6.0+r655-0ubuntu6_amd64.deb

script:
  - rebar compile

after_success:
  - rebar eunit
